language: ruby

sudo: false

cache: bundler

addons:
  apt:
    packages:
    - bsdtar

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0

branches:
  only:
    - master

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script: bundle exec rake test:unit
